### ISSUE TITLE
doctrine/annotations version conflict

### ISSUE THREAD

**Issue by MartkCz** [nettrine/annotations#5]
I want try nettrine instead of kdyby, but I have composer error.

My composer.json
```json
"nettrine/orm": "dev-master",
"nettrine/dbal": "dev-master",
"nettrine/annotations": "dev-master",
```

Error:
```
    - Installation request for nettrine/orm dev-master -> satisfiable by nettrine/orm[dev-master].
    - Can only install one of: doctrine/annotations[v1.6.0, v1.4.0].
    - nettrine/annotations dev-master requires doctrine/annotations 1.4.0 -> satisfiable by doctrine/annotations[v1.4.0].
    - nettrine/orm dev-master requires doctrine/annotations ~1.6.0 -> satisfiable by doctrine/annotations[v1.6.0].
    - Installation request for nettrine/annotations dev-master -> satisfiable by nettrine/annotations[dev-master].

```

**Comment by f3l1x** [comment]
Hi, do you really need nettrine/annotations? This package is suitable for writing your own annotations. 

There is a special extension just for ORM.

Take a look - https://github.com/nettrine/orm/tree/master/.docs#minimal-configuration

```yaml
extensions:
    orm.annotations: Nettrine\ORM\DI\OrmAnnotationsExtension

orm.annotations:
    paths:
        - App/Model/Database/Entity
```
